version: '3'

networks: 
  craft:

services:
  php:
    build: 
      context: .
      dockerfile: php.dockerfile
    container_name: php
    ports: 
      - "9000:9000"
    volumes: 
      - ./src:/var/www/html
    networks: 
      - craft
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    ports: 
      - "3306:3306"
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: craftdb
      MYSQL_USER: craft
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks: 
      - craft
  nginx:
    image: nginx:latest
    container_name: ngnix
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
    networks: 
      - craft
  composer: 
    image: composer:latest
    container_name: composer
    volumes: 
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - craft
  craft: 
    build: 
      context: .
      dockerfile: php.dockerfile
    container_name: craft
    volumes: 
      - ./src:/var/www/html
    depends_on: 
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/craft']
    networks: 
      - craft